#!/bin/bash

#PAN TRISTE
#mega-get "https://mega.nz/file/lgkkGZIA#mBvjItUvP03E84TUSqnB_0aOgt0uZUESc_SHQUR-D_E"

#GARFIELD
#youtube-dl "https://www1399.ff-03.com/token=z_isedI3WbmtgxLdXIgjQA/1618639397/152.171.0.0/5/9/36/0c472f8aa385e486b07a65deced53369-480p.mp4"

#ALADAR
#youtube-dl "https://www1001.ff-03.com/token=6dIs-U8ieA7UDU3Spky5Og/1618639523/152.171.0.0/5/9/2b/84f157e063eb8ec0363f0ac9e97832b9-480p.mp://www1001.ff-03.com/token=6dIs-U8ieA7UDU3Spky5Og/1618639523/152.171.0.0/5/9/2b/84f157e063eb8ec0363f0ac9e97832b9-480p.mp4"

#BEE MOVIE
#youtube-dl "https://www1276.ff-03.com/token=cfBS1jiBRyuOTkbg_GhZIg/1618639617/152.171.0.0/19/6/ca/e1b76b8205bb6e9684ed6f5941bc9ca6-480p.mp4"

VPLAYER="mpv"

yt_url=$(grep 'youtube' youtube-db)
echo "${yt_url}"

dialog --title "Peliculas" --msgbox "Iniciando programa" 5 25

while true; do
		option=$(dialog --menu "Ver pelicula" 0 0 0 \
				1 "Wallace"\
				2 "Bee movie"\
				3 "opcion3"\
				3>&2 2>&1 1>&3)
		case "$option" in
				1) clear; "$VPLAYER" "media/wallace.mp4" ;;
				2) clear; "$VPLAYER" "media/bee.mp4";;
				*) echo "Error end of program";;

		esac
		exit
done
